---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: "{{ cluster.name }}"

nodes:
  - role: control-plane
  - role: worker
    labels:
      ingress-node: bgp
  - role: worker
    labels:
      ingress-node: bgp
  - role: worker
    labels:
      ingress-node: bgp

networking:
  disableDefaultCNI: true
  kubeProxyMode: none