---
- block:
  - name: checking if kind cluster exists
    shell: "kind get clusters | grep kubernetes-base-cluster"
    register: kind_list_cmd
    failed_when: false
    ignore_errors: true      

  - name: setting up kind cluster
    command: "kind create cluster --config {{ role_path }}/files/cluster.yaml"
    when: kind_list_cmd.stdout == ""