---
- name: render frr.conf
  shell: "gotcli render -j \"$(docker network inspect kind)\" \"$(cat {{ role_path }}/files/frr/frr.conf.gotemplate)\" > {{ role_path }}/files/frr/frr.conf"

- name: creating frr docker container
  community.docker.docker_container:
    name: frr
    state: started
    restart: true
    restart_policy: unless-stopped
    image: quay.io/frrouting/frr:8.5.2
    volumes:
      - "{{ role_path }}/files/frr/:/etc/frr/"
    capabilities:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: host