---
- name: add Longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    force_update: true
    repo_url: https://charts.longhorn.io

- name: creating Longhorn namespace
  kubernetes.core.k8s:
    name: longhorn
    api_version: v1
    kind: Namespace
    state: present

- name: install Longhorn
  kubernetes.core.helm:
    name: longhorn
    namespace: longhorn
    chart_ref: longhorn/longhorn
    chart_version: 1.5.0
    values: "{{ lookup('template', 'longhorn/values.yaml') | from_yaml }}" 

- name: creating IngressRoute for Longhorn dashboard
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'longhorn/ingress.yaml') | from_yaml }}"
