---
- name: add Traefik chart repo
  kubernetes.core.helm_repository:
    name: traefik
    force_update: true
    repo_url: https://traefik.github.io/charts

- name: creating a Traefik namespace
  kubernetes.core.k8s:
    name: traefik
    api_version: v1
    kind: Namespace
    state: present

- name: install Traefik
  kubernetes.core.helm:
    name: traefik
    namespace: traefik
    chart_ref: traefik/traefik
    chart_version: 23.1.0
    values: "{{ lookup('template', 'traefik/values.yaml') | from_yaml }}" 

- name: enable Traefik dashboard
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'traefik/dashboard.yaml') | from_yaml_all }}"