---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
 name: bgp-peering
spec: 
  nodeSelector:
    matchLabels:
      bgp-peering: 'true'
  virtualRouters: 
    - localASN: 65100
      serviceSelector:
        matchExpressions:
           - {key: somekey, operator: NotIn, values: ['never-used-value']}
      neighbors: 
        - peerAddress: 172.19.0.1/32
          peerASN: 65100