---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
 name: bgp-peering
spec: 
  nodeSelector:
    matchLabels:
      ingress-node: "bgp"
  virtualRouters: 
    - localASN: {{ cluster.cilium.bgp.asn }}
      serviceSelector:
        matchExpressions: 
           - {key: somekey, operator: NotIn, values: ['never-used-value']} # match all nodes
      neighbors: 
        - peerAddress: "{{ cluster.cilium.bgp.tor_ip }}"
          peerASN: {{ cluster.cilium.bgp.asn }}