---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubernetes-base-cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
    labels:
      has-storage: true
networking:
  disableDefaultCNI: true
  kubeProxyMode: none