---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`longhorn.{{ cluster.hostname }}`)
    kind: Rule
    services:
    - name: longhorn-frontend
      port: 80