---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`hubble.{{ cluster.hostname }}`)
    kind: Rule
    services:
    - name: hubble-ui
      port: 80